stages:
    - build
    - publish

build:GuidIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet pack ./StronglyTyped.GuidIds --include-source --include-symbols --output ../GuidIds"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - GuidIds

publish:GuidIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: publish
    when: manual
    script:
        - "PackagePath=./GuidIds/"
        - "PackagePath+=$(ls ./GuidIds | head -1)"
        - "dotnet nuget push $PackagePath --api-key=$NugetKey --source=$Source"
