stages:
    - build
    - publish

build:StronglyTyped.GuidIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet pack ./StronglyTyped.GuidIds --include-source --include-symbols --output ../GuidIds"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - GuidIds

publish:StronglyTyped.GuidIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: publish
    when: manual
    script:
        - "PackagePath=$(ls ./GuidIds | head -1)"
        - "dotnet nuget push $PackagePath -k $NugetKey -s https://api.nuget.org/v3/index.json"

build:StronglyTyped.GuidIds.Dapper:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet pack StronglyTyped.GuidIds.Dapper -o ../GuidIds.Dapper"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - GuidIds.Dapper

publish:StronglyTyped.GuidIds.Dapper:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: publish
    when: manual
    script:
        - "PackagePath=$(ls ./GuidIds.Dapper | head -1)"
        - "dotnet nuget push $PackagePath -k $NugetKey -s https://api.nuget.org/v3/index.json"

build:StronglyTyped.IntIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet pack StronglyTyped.IntIds -o ../IntIds"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - IntIds

publish:StronglyTyped.IntIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: publish
    when: manual
    script:
        - "PackagePath=$(ls ./IntIds | head -1)"
        - "dotnet nuget push $PackagePath -k $NugetKey -s https://api.nuget.org/v3/index.json"

build:StronglyTyped.IntIds.Dapper:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet pack StronglyTyped.IntIds.Dapper -o ../IntIds.Dapper"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - IntIds.Dapper

publish:StronglyTyped.IntIds.Dapper:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: publish
    when: manual
    script:
        - "PackagePath=$(ls ./IntIds.Dapper | head -1)"
        - "dotnet nuget push $PackagePath -k $NugetKey -s https://api.nuget.org/v3/index.json"

build:StronglyTyped.LongIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet pack StronglyTyped.LongIds -o ../LongIds"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - LongIds

publish:StronglyTyped.LongIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: publish
    when: manual
    script:
        - "PackagePath=$(ls ./LongIds | head -1)"
        - "dotnet nuget push $PackagePath -k $NugetKey -s https://api.nuget.org/v3/index.json"

build:StronglyTyped.LongIds.Dapper:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet pack StronglyTyped.LongIds.Dapper -o ../LongIds.Dapper"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - LongIds.Dapper

publish:StronglyTyped.LongIds.Dapper:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: publish
    when: manual
    script:
        - "PackagePath=$(ls ./LongIds.Dapper | head -1)"
        - "dotnet nuget push $PackagePath -k $NugetKey -s https://api.nuget.org/v3/index.json"

build:StronglyTyped.StringIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet pack StronglyTyped.StringIds -o ../StringIds"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - StringIds

publish:StronglyTyped.StringIds:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: publish
    when: manual
    script:
        - "PackagePath=$(ls ./StringIds | head -1)"
        - "dotnet nuget push $PackagePath -k $NugetKey -s https://api.nuget.org/v3/index.json"

build:StronglyTyped.StringIds.Dapper:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet pack StronglyTyped.StringIds.Dapper -o ../StringIds.Dapper"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - StringIds.Dapper

publish:StronglyTyped.StringIds.Dapper:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: publish
    when: manual
    script:
        - "PackagePath=$(ls ./StringIds.Dapper | head -1)"
        - "dotnet nuget push $PackagePath -k $NugetKey -s https://api.nuget.org/v3/index.json"